version: "3.9"
services:
  pip-app:
    image: shaposhnikovmv/pip-app:1
    ports: ["5000:5000"]
    networks:
     - pip-app-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 1G
  haproxy-service:
    image: haproxytech/haproxy-debian:2.0
    ports:
      - 80:80
    networks: 
      - pip-app-network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
       condition: on-failure      
    volumes:
      - /etc/haproxy/:/etc/haproxy/:ro
    dns:
       - 127.0.0.11
networks:
  pip-app-network:
   driver: overlay
 
